/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import modelPath from '../../../models/office_merged.glb';
import matcapPath from '../../../img/matcap.png';
import { useFrame } from '@react-three/fiber';
import { lerp } from 'three/src/math/MathUtils';
import { gsap, Power2 } from 'gsap';
import useStore from '../../../store';

export default function Office(props) {
  const group = useRef();
  const ref = useRef();

  const view = useStore((state) => state.view);
  const leavingIpad = useStore((state) => state.leavingIpad);

  useEffect(() => {
    if (view === 'aboutEntered' && !leavingIpad) {
      gsap.to(ref.current.scale, {
        x: 1,
        y: 1,
        z: 1,

        delay: 0.5,
        ease: Power2.easeOut,
        duration: 0.5,
      });
    } else if (leavingIpad) {
      gsap.to(ref.current.scale, {
        x: 0,
        y: 0,
        z: 0,

        ease: Power2.easeOut,
        duration: 0.5,
      });
    }
  }, [view, leavingIpad]);

  const { nodes } = useGLTF(modelPath);

  const texture = useTexture(matcapPath);

  useFrame(({ clock, mouse }) => {
    let ry = props.rotation[1];

    let [, py] = props.position;

    if (group.current) {
      group.current.rotation.y = ry + Math.sin(clock.elapsedTime * 0.25) * 0.25;

      group.current.position.y = py + Math.cos(clock.elapsedTime * 0.35) * 0.15;
    }

    let x = mouse.x * 0.45;
    let y = mouse.y * 0.45;

    if (ref.current) {
      ref.current.position.x = lerp(ref.current.position.x, x, 0.015);
      ref.current.position.y = lerp(ref.current.position.y, y, 0.015);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.drawers001.geometry} scale={[0, 0, 0]}>
        <meshMatcapMaterial matcap={texture} transparent={true} />
      </mesh>
    </group>
  );
}

useGLTF.preload(modelPath);
